use std::{fs, path::PathBuf};

fn repo_doc(path: &str) -> String {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let doc_path = manifest_dir.join("../..").join(path);
    fs::read_to_string(&doc_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", doc_path.display()))
}

fn contains_ci(haystack: &str, needle: &str) -> bool {
    haystack
        .to_ascii_lowercase()
        .contains(&needle.to_ascii_lowercase())
}

fn has_all_ci(haystack: &str, needles: &[&str]) -> bool {
    needles.iter().all(|needle| contains_ci(haystack, needle))
}

fn has_any_ci(haystack: &str, needles: &[&str]) -> bool {
    needles.iter().any(|needle| contains_ci(haystack, needle))
}

fn assert_contains_all_ci(haystack: &str, needles: &[&str]) {
    for needle in needles {
        assert!(
            contains_ci(haystack, needle),
            "expected to find {needle:?} in:\n{haystack}"
        );
    }
}

fn assert_contains_any_ci(haystack: &str, needles: &[&str]) {
    assert!(
        has_any_ci(haystack, needles),
        "expected to find one of {needles:?} in:\n{haystack}"
    );
}

fn assert_not_contains_ci(haystack: &str, needle: &str) {
    assert!(
        !contains_ci(haystack, needle),
        "did not expect to find {needle:?} in:\n{haystack}"
    );
}

fn line_containing<'a>(haystack: &'a str, needle: &str) -> Option<&'a str> {
    haystack.lines().find(|line| contains_ci(line, needle))
}

fn context_containing(haystack: &str, needle: &str) -> Option<String> {
    line_containing(haystack, needle)
        .map(str::to_string)
        .or_else(|| {
            haystack
                .split("\n\n")
                .find(|paragraph| contains_ci(paragraph, needle))
                .map(str::to_string)
        })
}

fn contexts_containing_any(haystack: &str, needles: &[&str]) -> Vec<String> {
    let mut contexts = Vec::new();
    for line in haystack.lines() {
        if needles.iter().any(|needle| contains_ci(line, needle)) {
            contexts.push(line.to_string());
        }
    }
    for paragraph in haystack.split("\n\n") {
        if needles.iter().any(|needle| contains_ci(paragraph, needle))
            && !contexts.iter().any(|context| context == paragraph)
        {
            contexts.push(paragraph.to_string());
        }
    }
    contexts
}

fn assert_matching_context<F>(
    haystack: &str,
    anchors: &[&str],
    description: &str,
    matches: F,
) -> String
where
    F: Fn(&str) -> bool,
{
    let contexts = contexts_containing_any(haystack, anchors);
    for context in &contexts {
        if matches(context) {
            return context.to_string();
        }
    }
    panic!(
        "expected context for {description}; inspected contexts:\n{}",
        contexts.join("\n---\n")
    );
}

fn section_between<'a>(haystack: &'a str, start: &str, next: &str) -> &'a str {
    let Some(start_index) = haystack.find(start) else {
        return haystack;
    };
    let section_start = start_index + start.len();
    let after_start = &haystack[section_start..];
    match after_start.find(next) {
        Some(next_index) => &after_start[..next_index],
        None => after_start,
    }
}

#[test]
fn status_index_no_longer_marks_005_as_active_planning() {
    let readme = repo_doc("specs/README.md");
    let status = repo_doc("docs/spec-status.md");

    let readme_row = line_containing(&readme, "005-v2-spec-conformance-gaps")
        .expect("specs/README.md must list the 005 cleanup feature");
    assert_not_contains_ci(readme_row, "active planning");
    assert_not_contains_ci(readme_row, "planned");
    assert_contains_any_ci(
        readme_row,
        &[
            "complete",
            "completed",
            "closed",
            "implemented",
            "shipped",
            "done",
        ],
    );

    let status_005 = section_between(
        &status,
        "## 005 Implementation Status",
        "## 004 Implementation Status",
    );
    for unresolved in [
        "User-visible legacy runtime fallback still selectable for v2 work | Planned",
        "Add-step scope-expansion review card generated by frontend rule card instead of SupervisorAgent path | Planned",
        "Step-rationale challenge logs objection but does not offer plan adjustment/re-decomposition | Planned",
        "`change_step` / `retire_step` mutation behavior reserved in contracts but easy to misread as shipped | Planned documentation clarification",
        "003 card UX status needs truthful completion/harmonization accounting | Planned documentation clarification",
    ] {
        assert_not_contains_ci(status_005, unresolved);
    }

    for anchor in [
        "legacy runtime fallback",
        "scope-expansion",
        "scope expansion",
        "rationale challenge",
        "change_step",
        "retire_step",
        "003 card UX",
        "harmonization",
    ] {
        for context in contexts_containing_any(status_005, &[anchor]) {
            assert_not_contains_ci(&context, "planned");
        }
    }
}

#[test]
fn status_ledger_identifies_s017_through_s020_outcomes() {
    let status = repo_doc("docs/spec-status.md");

    let stage_expectations = [
        (
            "S-017",
            &["runtime"][..],
            &["legacy", "fallback", "capability"][..],
        ),
        (
            "S-018",
            &["scope"][..],
            &["SupervisorAgent", "supervisor"][..],
        ),
        (
            "S-019",
            &["rationale", "offer"][..],
            &["plan", "adjustment"][..],
        ),
        (
            "S-020",
            &["status"][..],
            &["docs", "documentation", "spec"][..],
        ),
    ];

    let outcome_terms = [
        "done",
        "complete",
        "completed",
        "closed",
        "validated",
        "shipped",
    ];
    for (stage, required_terms, topic_terms) in stage_expectations {
        let description = format!("{stage} outcome");
        assert_matching_context(&status, &[stage], &description, |context| {
            has_all_ci(context, required_terms)
                && has_any_ci(context, topic_terms)
                && has_any_ci(context, &outcome_terms)
                && !contains_ci(context, "planned")
        });
    }
}

#[test]
fn shipped_mutation_types_are_labeled_shipped_under_s033() {
    // Retargeted from the 005/S-020 "truthful active spec status" guard. S-033
    // (009 theme 5) shipped both the remove path (`retire_step` /
    // `plan_step_retired`) and the supersede path (`change_step` /
    // `plan_step_changed`) as visible, tested apply IPCs. The status docs must
    // now describe these mutations as shipped under S-033, and must never
    // relabel them future/contract-reserved, not shipped, or planned.
    let docs = format!(
        "{}\n{}",
        repo_doc("docs/spec-status.md"),
        repo_doc("specs/README.md")
    );

    for mutation_type in ["change_step", "retire_step"] {
        let primary = context_containing(&docs, mutation_type)
            .unwrap_or_else(|| panic!("status docs must mention {mutation_type}"));
        assert_contains_all_ci(&primary, &["shipped", "S-033"]);

        for context in contexts_containing_any(&docs, &[mutation_type]) {
            assert_not_contains_ci(&context, "contract-reserved");
            assert_not_contains_ci(&context, "not shipped");
            assert_not_contains_ci(&context, "planned");
        }
    }
}

#[test]
fn status_docs_name_closed_and_clarified_005_gaps() {
    let docs = format!(
        "{}\n{}",
        repo_doc("docs/spec-status.md"),
        repo_doc("specs/README.md")
    );

    assert_matching_context(
        &docs,
        &["legacy runtime fallback"],
        "legacy runtime fallback removed or blocked",
        |context| {
            has_any_ci(
                context,
                &["removed", "no user-visible", "blocked", "closed"],
            )
        },
    );

    assert_matching_context(
        &docs,
        &["scope-expansion", "scope expansion"],
        "scope-expansion SupervisorAgent path outcome",
        |context| {
            has_any_ci(context, &["SupervisorAgent", "supervisor"])
                && has_any_ci(
                    context,
                    &["closed", "complete", "completed", "shipped", "validated"],
                )
        },
    );

    assert_matching_context(
        &docs,
        &["rationale"],
        "rationale challenge non-blocking plan-adjustment offer",
        |context| {
            has_all_ci(context, &["offer"])
                && has_any_ci(
                    context,
                    &["non-blocking", "plan-adjustment", "plan adjustment"],
                )
        },
    );

    assert_matching_context(
        &docs,
        &["003", "card UX"],
        "003 presentation and harmonization status",
        |context| {
            has_all_ci(context, &["presentation"])
                && has_any_ci(context, &["harmonization", "harmonisation"])
                && has_any_ci(
                    context,
                    &["remaining", "partial", "complete", "completed", "clarified"],
                )
        },
    );
}
